const constants = {
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILED:"LOGIN_FAILED",
  LOGUOT:"LOGOUT",
  PROFILE_SUCCESS:"PROFILE_SUCCESS",
  PROFILE_FAILED:"ROFILE_FAILED",
  NEWS_SUCCESS:"NEWS_SUCCESS",
  NEWS_FAILED:"NEWS_FAILED"
}

export default constants;